const info = [
    {nome: 'nome do estado', main: 'informação interessante aqui', conteudo: 'conteúdo cultural do estado'},
    {nome: 'Roraima (RO)', main: '', conteudo: ''},
    {nome: 'Amapá (AP)', main: '', conteudo: ''},
    {nome: 'Pará (PA)', main: 'berço da cultura marajoara', conteudo: 'Você sabia que no Pará chove 3 dias sim e 3 dias também?'},
    {nome: 'Amazonas (AM)', main: '', conteudo: ''},
    {nome: 'Maranhão (MA)', main: '', conteudo: ''},
    {nome: 'Piaui (PI)', main: '', conteudo: ''},
    {nome: 'Ceará (CE)', main: '', conteudo: ''},
    {nome: 'Tocantins (TO)', main: '', conteudo: ''},
    {nome: 'Rio Grande do Norte (RN)', main: '', conteudo: ''},        
    {nome: 'Paraíba (PB)', main: '', conteudo: ''},
    {nome: 'Mato Grosso (MT)', main: '', conteudo: ''},
    {nome: 'Pernambuco (PE)', main: '', conteudo: ''},
    {nome: 'Acre (AC)', main: 'dinossauros', conteudo: ''},
    {nome: 'Rondônia (RO)', main: '', conteudo: ''},
    {nome: 'Bahia (BA)', main: '', conteudo: ''},
    {nome: 'Alagoas (AL)', main: '', conteudo: ''},
    {nome: 'Sergipe (SE)', main: '', conteudo: ''},
    {nome: 'Goiás (GO)', main: '', conteudo: ''},
    {nome: 'Minas Gerais (MG)', main: '', conteudo: ''},
    {nome: 'Distrito Federal (DF)', main: '', conteudo: ''},
    {nome: 'Mato Grosso do Sul (MS)', main: '', conteudo: ''},
    {nome: 'Espírito Santo (ES)', main: '', conteudo: ''},
    {nome: 'São Paulo (SP)', main: '', conteudo: ''},
    {nome: 'Rio de Janeiro (RJ)', main: '', conteudo: ''},
    {nome: 'Paraná (PR)', main: '', conteudo: ''},
    {nome: 'Santa Catarina (SC)', main: '', conteudo: ''},
    {nome: 'Rio Grande so Sul (RS)', main: '', conteudo: ''},
    {nome: 'Curiosidade', main: 'intro', conteudo: 'explicação'}
]

export default info;